// import imgcard from './productCard.png';
import imgcard from "../../assets/images/productCard.png";

const like = false; // Здесь определите значение like

const data = [
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "180.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "120.000 uzs",
    isLiked: like,
    id: 0,
  },
  {
    img: imgcard,
    title: "Перчатки Боксерские ФТБР",
    newcost: "200.000 uzs",
    isLiked: like,
    id: 0,
  },
];

export default data;
